/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutServer: typeof import('./src/components/AboutServer.vue')['default']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    Account: typeof import('./src/components/Account.vue')['default']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AllNews: typeof import('./src/components/AllNews.vue')['default']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARate: typeof import('ant-design-vue/es')['Rate']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    CatalogCategory: typeof import('./src/components/CatalogCategory.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Landing: typeof import('./src/components/Landing.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MerchShop: typeof import('./src/components/MerchShop.vue')['default']
    PageNotFound: typeof import('./src/components/PageNotFound.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    Players: typeof import('./src/components/Players.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    Product: typeof import('./src/components/Product.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
