/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutServer: typeof import('./src/components/AboutServer.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    Account: typeof import('./src/components/Account.vue')['default']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Landing: typeof import('./src/components/Landing.vue')['default']
    MerchShop: typeof import('./src/components/MerchShop.vue')['default']
    PageNotFound: typeof import('./src/components/PageNotFound.vue')['default']
    Players: typeof import('./src/components/Players.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
