import { ref } from 'vue'

const products = ref([
    {
        product_id:'1',
        category_id:'stickers',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/stickers.jpg`,
        name: 'Стикеры - NOW 1 сезон',
        description: '',
        price: 10,
        status:'Скоро в продаже',
    },
    {
        product_id:'2',
        category_id:'postcards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/panda.jpg`,
        name: 'Открытка - Pandalin “Лето”',
        description: '',
        price: 10,
        status:'Возможен предзаказ',
    },
    {        
        product_id:'3',
        category_id:'postcards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/kind_kail.jpg`,
        name: 'Открытка - KailDC ”Добрый модер”',
        description: '',
        price: 10,
        status:'Скоро в продаже',
    },
    {
        product_id:'4',
        category_id:'postcards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/just_rana.jpg`,
        name: 'Открытка - Raniya ”Просто Раниш”',
        description: '',
        price: 10,
        status:'Скоро в продаже',
    },
    {
        product_id:'5',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (4 шт.)',
        description: '',
        price: 5,
        status:'Скоро в продаже',
    },
    {
        product_id:'6',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (6 шт.)',
        description: '',
        price: 10,
        status:'Скоро в продаже',
    },
    {
        product_id:'7',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (8 шт.)',
        description: '',
        price: 15,
        status:'Скоро в продаже',
    },
    {
        product_id:'8',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (12 шт.)',
        description: '',
        price: 20,
        status:'Скоро в продаже',
    },
    {
        product_id:'9',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (12 шт.)',
        description: '',
        price: 20,
        status:'Скоро в продаже',
    },
    {
        product_id:'10',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (12 шт.)',
        description: '',
        price: 20,
        status:'Скоро в продажеa',
    },
])

export {products}