import { ref } from 'vue'

const products = ref([
    {
        product_id:'',
        category_id:'stickers',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/stickers.jpg`,
        name: 'Стикеры - NOW 1 сезон',
        description: '',
        price: 10,
        status:'Скоро в продаже',
    },
    {
        product_id:'',
        category_id:'postcards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/panda.jpg`,
        name: 'Открытка - Pandalin “Лето”',
        description: '',
        price: 10,
        status:'Скоро в продаже',
    },
    {        
        product_id:'',
        category_id:'postcards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/kind_kail.jpg`,
        name: 'Открытка - KailDC ”Добрый модер”',
        description: '',
        price: 10,
        status:'Скоро в продаже',
    },
    {
        product_id:'',
        category_id:'postcards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/exegs_cute.jpg`,
        name: 'Открытка - ExEGS ”Просто робот”',
        description: '',
        price: 10,
        status:'Скоро в продаже',
    },
    {
        product_id:'',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (4 шт.)',
        description: '',
        price: 5,
        status:'Скоро в продаже',
    },
    {
        product_id:'',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (6 шт.)',
        description: '',
        price: 10,
        status:'Скоро в продаже',
    },
    {
        product_id:'',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (8 шт.)',
        description: '',
        price: 15,
        status:'Скоро в продаже',
    },
    {
        product_id:'',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (12 шт.)',
        description: '',
        price: 20,
        status:'Скоро в продаже',
    },
    {
        product_id:'',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (12 шт.)',
        description: '',
        price: 20,
        status:'Скоро в продаже',
    },
    {
        product_id:'',
        category_id:'cards',
        pic: `${import.meta.env.VITE_BASE_URL}/src/assets/cards.png`,
        name: 'Набор тематических карточек (12 шт.)',
        description: '',
        price: 20,
        status:'Скоро в продажеa',
    },
])

export {products}